[package]
name = "ccls"
version = "0.1.0"
authors = ["Tim Kilbourn <tkilbourn@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"
csv = "1.1"
